'\" t
.\"     Title: radeontop
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/30/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "RADEONTOP" "1" "09/30/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
radeontop \- tool to show GPU utilization
.SH "SYNOPSIS"
.sp
\fBradeontop [\-chmv] [\-b \fR\fB\fIbus\fR\fR\fB] [\-d \fR\fB\fIfile\fR\fR\fB] [\-l \fR\fB\fIlimit\fR\fR\fB] [\-i \fR\fB\fIsecs\fR\fR\fB] [\-p \fR\fB\fIdevice\fR\fR\fB] [\-t \fR\fB\fIticks\fR\fR\fB]\fR
.SH "DESCRIPTION"
.sp
RadeonTop shows the utilization of your GPU, both in general and by blocks\&.
.sp
Supported cards are R600 and up\&.
.SH "OPTIONS"
.PP
\fB\-b, \-\-bus \fR\fB\fIbus\fR\fR
.RS 4
If you have multiple cards, use this parameter to select a specific one\&. For lspci output
\fI01:00\&.0 VGA compatible controller\fR, bus would be
\fI1\fR\&.
.RE
.PP
\fB\-c, \-\-color\fR
.RS 4
Enables colorized output\&.
.RE
.PP
\fB\-d, \-\-dump \fR\fB\fIfile\fR\fR
.RS 4
Instead of displaying the data, dump it to
\fIfile\fR\&. Use
\fI\-\fR
for stdout\&. The file is appended to, so it\(cqs safe to specify the same filename for consecutive runs\&.

Use
\fISIGTERM\fR
or
\fISIGINT\fR
for graceful termination\&.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Displays help\&.
.RE
.PP
\fB\-i, \-\-dump\-interval \fR\fB\fIseconds\fR\fR
.RS 4
Wait for N seconds between data output\&.
.RE
.PP
\fB\-l, \-\-limit \fR\fB\fIlimit\fR\fR
.RS 4
Quit after dumping
\fIlimit\fR
lines\&. Only valid in dump mode\&. Default is to dump until terminated; use
\fISIGTERM\fR
or
\fISIGINT\fR
for graceful termination\&.
.RE
.PP
\fB\-m, \-\-mem\fR
.RS 4
Forces the use of the /dev/mem path, in case autodetection fails\&. Useful for the proprietary driver\&.
.RE
.PP
\fB\-p, \-\-path \fR\fB\fIdevice\fR\fR
.RS 4
Open the DRM device node specified by
\fIdevice\fR
path\&. Usually it is located at /dev/dri/card0 or /dev/drm0\&. If this option used, \-\-bus and \-\-mem are ignored\&.
.RE
.PP
\fB\-t, \-\-ticks \fR\fB\fIticks\fR\fR
.RS 4
How many times per second to sample the data\&. The default is 120\&. Higher numbers mean more accurate output and more overhead\&.
.RE
.PP
\fB\-v, \-\-version\fR
.RS 4
Displays the program version\&.
.RE
.SH "INTERACTIVE COMMANDS"
.PP
\fBC, c\fR
.RS 4
Toggle colorized output\&.
.RE
.PP
\fBQ, q\fR
.RS 4
Quit\&.
.RE
.SH "RESOURCES"
.sp
See http://github\&.com/clbr/radeontop
